apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /coo(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: coo-service
            port:
              number: 80
      - path: /like(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: like-service
            port:
              number: 80
      - path: /follow(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: follow-service
            port:
              number: 80
      - path: /user(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /reply(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: reply-service
            port:
              number: 80
      - path: /search(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-service
            port:
              number: 80
      - path: /personalize(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: personalize-service
            port:
              number: 80