kubectl delete -f k8s/statistics-service.yaml
kubectl delete -f k8s/statistics-service-deployment.yaml
kubectl delete -f k8s/personalize-service.yaml
kubectl delete -f k8s/personalize-service-deployment.yaml
kubectl delete -f k8s/search-service.yaml
kubectl delete -f k8s/search-service-deployment.yaml
kubectl delete -f k8s/follow-service.yaml
kubectl delete -f k8s/follow-service-deployment.yaml
kubectl delete -f k8s/like-service.yaml
kubectl delete -f k8s/like-service-deployment.yaml
kubectl delete -f k8s/reply-service.yaml
kubectl delete -f k8s/reply-service-deployment.yaml
kubectl delete -f k8s/coo-service.yaml
kubectl delete -f k8s/coo-service-deployment.yaml
kubectl delete -f k8s/user-service.yaml
kubectl delete -f k8s/user-service-deployment.yaml
kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml
kubectl delete -f k8s/ingress.yaml
kubectl delete secret db-credentials
kubectl delete -f k8s/postgres-service.yaml
kubectl delete -f k8s/postgres-deployment.yaml
kubectl delete -f k8s/postgres-pvc.yaml
kubectl delete -f k8s/postgres-persistent-volume.yaml